import { GoogleGenAI } from "@google/genai";
import { DetectionResult, Transaction } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

export const analyzeImage = async (base64Image: string): Promise<DetectionResult> => {
  const model = ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: [
      {
        parts: [
          { text: "Analyze this image and determine the likelihood that it was generated by an AI (like Midjourney, DALL-E, or Stable Diffusion). Provide a probability percentage (0-100) where 100 means definitely AI-generated and 0 means definitely human-captured/created. Also provide a brief technical explanation of your findings (e.g., artifacts, lighting, textures). Return the result in JSON format with keys 'isAI' (boolean, true if probability > 50), 'probability' (number), and 'explanation' (string)." },
          { inlineData: { mimeType: "image/jpeg", data: base64Image.split(',')[1] } }
        ]
      }
    ],
    config: {
      responseMimeType: "application/json"
    }
  });

  const response = await model;
  return JSON.parse(response.text || "{}");
};

export const verifyTransaction = async (transaction: Partial<Transaction>): Promise<{ isSuspicious: boolean; riskScore: number; reason: string }> => {
  const model = ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: `Analyze this transaction for potential fraud or suspicious activity: ${JSON.stringify(transaction)}. 
    Consider amount, location, merchant, and common fraud patterns. 
    Return the result in JSON format with keys 'isSuspicious' (boolean), 'riskScore' (number from 0-100), and 'reason' (string explanation).`,
    config: {
      responseMimeType: "application/json"
    }
  });

  const response = await model;
  return JSON.parse(response.text || "{}");
};
